name: Dependency Track Upload

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_call:
    secrets:
      DEPENDENCYTRACK_API_KEY:
        required: true

jobs:
  php_sbom:
    name: Generate PHP SBOM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            extensions: xml, mbstring
            tools: composer:v2
        env:
            COMPOSER_TOKEN: ${{ inputs.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        run: |
          composer global config --no-plugins allow-plugins.cyclonedx/cyclonedx-php-composer true
          composer global require cyclonedx/cyclonedx-php-composer

      - name: Generate BoM
        run: |
          composer CycloneDX:make-sbom --output-file sbom-php.xml --spec-version="1.2"
      
      # - name: Store PHP/Composer SBOM
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: sbom-php
      #     path: sbom-php.xml
      #     retention-days: 5

      - name: Upload to Depdenency Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverHostname: ${{ vars.DEPENDENCYTRACK_API }}
          apiKey: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
          projectName: PHP/Composer
          projectVersion: ${{ github.ref_name}}
          parentName: ${{ github.event.repository.name }}
          parentVersion: ${{ github.ref_name}}
          bomFilename: "sbom.json"
          autoCreate: true

  npm_sbom:
    name: Generate NPM SBOM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM
        uses: actions/setup-node@v4

      - name: Install NPM modules
        run: |
          npm install
          npm audit fix --force

      - name: Install NPM dependencies
        run: npm install -g @cyclonedx/cyclonedx-npm

      - name: Generate BoM
        run: cyclonedx-npm --output-format xml --output-file sbom-npm.xml --spec-version 1.2
      
      # - name: Store NPM SBOM
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: sbom-npm
      #     path: sbom-npm.xml
      #     retention-days: 5
      

      - name: Upload to Depdenency Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverHostname: ${{ vars.DEPENDENCYTRACK_API }}
          apiKey: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
          projectName: NPM
          projectVersion: ${{ github.ref_name}}
          parentName: ${{ github.event.repository.name }}
          parentVersion: ${{ github.ref_name}}
          bomFilename: "sbom.json"
          autoCreate: true

  # merge_and_upload:
  #   name: Merge and Upload SBOM
  #   runs-on: ubuntu-latest

  #   needs: [
  #     php_sbom,
  #     npm_sbom
  #   ]

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Download SBOM Result files
  #       uses: actions/download-artifact@v4
  #       with:
  #         pattern: sbom-*
  #         path: ${{ github.workspace }}
  #         merge-multiple: true

  #     - name: Install required tools
  #       run: sudo apt-get install -y build-essential libxml2-utils

  #     - name: Install CycloneDX
  #       run: |
  #         wget -q https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64 -O /usr/local/bin/cyclonedx-cli
  #         chmod +x /usr/local/bin/cyclonedx-cli

  #     - name: Merge SBOMs
  #       run: cyclonedx-cli merge --input-files sbom-php.xml sbom-npm.xml --output-file sbom-merge.xml

  #     - name: Convert SBOM
  #       run: cyclonedx-cli convert --input-file sbom-merge.xml --output-file sbom.json --output-format json --output-version v1_2

  #     - name: Upload to Depdenency Track
  #       uses: DependencyTrack/gh-upload-sbom@v3
  #       with:
  #         serverHostname: ${{ vars.DEPENDENCYTRACK_API }}
  #         apiKey: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
  #         projectName: ${{ github.event.repository.name }}
  #         projectVersion: ${{ github.ref_name}}
  #         bomFilename: "sbom.json"
  #         autoCreate: true
