name: Dependency Track Upload

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_call:
    secrets:
      DEPENDENCYTRACK_API_KEY:
        required: true

jobs:
  php_sbom:
    name: Generate PHP SBOM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            extensions: xml, mbstring
            tools: composer:v2
        env:
            COMPOSER_TOKEN: ${{ inputs.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        run: |
          composer global config --no-plugins allow-plugins.cyclonedx/cyclonedx-php-composer true
          composer global require cyclonedx/cyclonedx-php-composer

      - name: Generate BoM
        run: |
          composer CycloneDX:make-sbom --output-file php-sbom.xml --spec-version="1.2"
          ls -la
      
      - name: Store PHP/Composer SBOM
        uses: actions/upload-artifact@v4
        with:
          name: php-sbom
          path: php-sbom.xml
          retention-days: 5

  npm_sbom:
    name: Generate NPM SBOM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM
        uses: actions/setup-node@v4

      - name: Install NPM modules
        run: |
          npm install
          npm audit fix --force

      - name: Install NPM dependencies
        run: npm install -g @cyclonedx/cyclonedx-npm

      - name: Generate BoM
        run: cyclonedx-npm --output-format xml --output-file npm-sbom.xml --spec-version 1.2
      
      - name: Store NPM SBOM
        uses: actions/upload-artifact@v4
        with:
          name: npm-sbom
          path: npm-sbom.xml
          retention-days: 5

  merge_and_upload:
    name: Merge and Upload SBOM
    runs-on: ubuntu-latest

    needs: [
      php_sbom,
      npm_sbom
    ]

    steps:
      - uses: actions/checkout@v4

      - name: Download PHP/Composer SBOM Result file
        uses: actions/download-artifact@v4
        with:
          name: php-sbom
          path: php-sbom.xml

      - name: Download NPM SBOM Result file
        uses: actions/download-artifact@v4
        with:
          name: npm-sbom
          path: npm-sbom.xml

      - name: Install required tools
        run: sudo apt-get install -y build-essential libxml2-utils

      - name: Install CycloneDX
        run: |
          wget -q https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64 -O /usr/local/bin/cyclonedx-cli
          chmod +x /usr/local/bin/cyclonedx-cli

      - name: Merge SBOMs
        run: |
          ls -la
          cyclonedx-cli merge --input-files php-sbom.xml npm-sbom.xml --output-file sbom_all.xml

      - name: Convert SBOM
        run: cyclonedx-cli convert --input-file sbom_all.xml --output-file sbom.json --output-format json --output-version v1_2

      - name: Upload to Depdenency Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverHostname: ${{ vars.DEPENDENCYTRACK_API }}
          apiKey: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
          projectName: ${{ github.event.repository.name }}
          projectVersion: ${{ github.ref_name}}
          bomFilename: "sbom.json"
          autoCreate: true
