name: Dependency Track Upload

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  php_sbom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            extensions: xml, mbstring
            tools: composer:v2
        env:
            COMPOSER_TOKEN: ${{ inputs.GITHUB_TOKEN }}

      - name: Install required tools
        run: sudo apt-get install -y build-essential libxml2-utils

      - name: Install CycloneDX
        run: |
          wget https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64 -O /usr/local/bin/cyclonedx-cli
          chmod +x /usr/local/bin/cyclonedx-cli

      - name: Install Composer dependencies
        run: |
          composer global config --no-plugins allow-plugins.cyclonedx/cyclonedx-php-composer true
          composer global require cyclonedx/cyclonedx-php-composer

      - name: Generate BoM
        run: |
          composer
          composer CycloneDX:make-sbom --output-file bom.xml --spec-version="1.2"
          cyclonedx-cli convert --input-file bom.xml --output-file sbom.xml --output-format json_v1_2
      
      - name: Upload to Depdenency Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverHostname: ${{ vars.DEPENDENCYTRACK_API }}
          apiKey: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
          projectName: ${{ github.repository }}
          projectVersion: ${{ github.ref_name }}
          bomFilename: "sbom.xml"
          autoCreate: true