name: Dependency Track Upload

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_call:
    inputs:
      version:
        type: string
      tags:
        type: string
      parentProjectUuid:
        type: string
    secrets:
      DEPENDENCYTRACK_API_KEY:
        required: true

jobs:
  php_sbom:
    name: Generate PHP SBOM
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            extensions: xml, mbstring
            tools: composer:v2
        env:
            COMPOSER_TOKEN: ${{ inputs.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        run: |
          composer global config --no-plugins allow-plugins.cyclonedx/cyclonedx-php-composer true
          composer global require cyclonedx/cyclonedx-php-composer

      - name: Generate BoM
        run: |
          composer CycloneDX:make-sbom --output-file sbom-php.xml --spec-version="1.2"

      - name: Install CycloneDX CLI
        run: |
          sudo apt-get install -y build-essential libxml2-utils
          wget -q https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64 -O /usr/local/bin/cyclonedx-cli
          chmod +x /usr/local/bin/cyclonedx-cli
      
      - name: Convert SBOM
        run: cyclonedx-cli convert --input-file sbom-php.xml --output-file sbom.json --output-format json --output-version v1_2

      - name: Add default tags
        run: |
          export TAGS="Language:PHP,PackageManager:Composer,Branch:${BRANCH_NAME}"
          if [ -n "${{ inputs.tags }}" ]; then
            export TAGS="${TAGS},${{ inputs.tags }}"
          elif [ -n "${{ vars.DEPENDENCYTRACK_TAGS }}" ]; then
            export TAGS="${TAGS},${{ vars.DEPENDENCYTRACK_TAGS }}"
          fi
          echo TAGS=$TAGS >> $GITHUB_ENV

      - name: Upload to Depdenency Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverhostname: ${{ vars.DEPENDENCYTRACK_API }}
          apikey: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
          projectname: ${{ github.event.repository.name }} PHP/Composer
          projectversion: ${{ inputs.version || github.ref_name }}
          parent: ${{ inputs.parentProjectUuid || vars.DEPENDENCYTRACK_PARENT_PROJECT_UUID }}
          projecttags: ${{ env.TAGS }}
          bomfilename: "sbom.json"
          autocreate: true

  npm_sbom:
    name: Generate NPM SBOM
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

    steps:
      - uses: actions/checkout@v4

      - name: Install NPM
        uses: actions/setup-node@v4

      - name: Install NPM modules
        run: |
          npm ci
          npm audit fix --force

      - name: Install NPM dependencies
        run: npm install -g @cyclonedx/cyclonedx-npm

      - name: Generate BoM
        run: cyclonedx-npm --output-format xml --output-file sbom-npm.xml --spec-version 1.2

      - name: Install CycloneDX CLI
        run: |
          sudo apt-get install -y build-essential libxml2-utils
          wget -q https://github.com/CycloneDX/cyclonedx-cli/releases/latest/download/cyclonedx-linux-x64 -O /usr/local/bin/cyclonedx-cli
          chmod +x /usr/local/bin/cyclonedx-cli
      
      - name: Convert SBOM
        run: cyclonedx-cli convert --input-file sbom-npm.xml --output-file sbom.json --output-format json --output-version v1_2

      - name: Add default tags
        run: |
          export TAGS="Language:NPM,PackageManager:NPM,Branch:${BRANCH_NAME}"
          if [ -n "${{ inputs.tags }}" ]; then
            export TAGS="${TAGS},${{ inputs.tags }}"
          elif [ -n "${{ vars.DEPENDENCYTRACK_TAGS }}" ]; then
            export TAGS="${TAGS},${{ vars.DEPENDENCYTRACK_TAGS }}"
          fi
          echo TAGS=$TAGS >> $GITHUB_ENV

      - name: Upload to Depdenency Track
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverhostname: ${{ vars.DEPENDENCYTRACK_API }}
          apikey: ${{ secrets.DEPENDENCYTRACK_API_KEY }}
          projectname: ${{ github.event.repository.name }} NPM
          projectversion: ${{ inputs.version || github.ref_name }}
          parent: ${{ inputs.parentProjectUuid || vars.DEPENDENCYTRACK_PARENT_PROJECT_UUID }}
          projecttags: ${{ inputs.tags }}
          bomfilename: "sbom.json"
          autocreate: true